# Generated by Django 4.2.5 on 2023-09-08 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_as_of', models.DateField(auto_created=True)),
                ('ref_code', models.CharField(max_length=255)),
                ('payment_receipt_image', models.ImageField(upload_to='images/')),
                ('amount_paid', models.FloatField()),
                ('payment_type', models.TextField(choices=[('WALK IN', 'WALK IN'), ('GCASH', 'GCASH'), ('PAYMAYA', 'PAYMAYA')])),
                ('date_paid', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
                'db_table': 'account_tbl',
            },
        ),
    ]
