# Generated by Django 4.2.5 on 2023-10-01 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='payment_receipt_image',
            field=models.ImageField(upload_to='media/profs'),
        ),
    ]
