# Generated by Django 4.2.5 on 2023-10-06 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_payment_receipt_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='payment_status',
            field=models.TextField(choices=[('PENDING', 'PENDING'), ('VERIFIED', 'VERIFIED'), ('DECLINED', 'DECLINED')], default='VERIFIED'),
            preserve_default=False,
        ),
    ]
