# Generated by Django 4.2.5 on 2023-10-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_account_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='payment_status',
            field=models.TextField(choices=[('PENDING', 'PENDING'), ('VERIFIED', 'VERIFIED'), ('DECLINED', 'DECLINED')], default=('PENDING', 'PENDING')),
        ),
    ]
