# Generated by Django 4.2.5 on 2023-11-03 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0008_alter_account_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='payment_as_of',
        ),
        migrations.RemoveField(
            model_name='account',
            name='payment_to',
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('due_date', models.DateField()),
                ('amount', models.IntegerField()),
                ('status', models.TextField(choices=[('PAID', 'PAID'), ('UNPAID', 'UNPAID')])),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Billing',
                'verbose_name_plural': 'Billings',
                'db_table': 'billing_tbl',
            },
        ),
    ]
