# Generated by Django 4.2.5 on 2023-11-03 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_account_payment_as_of_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='user_id',
        ),
    ]
