# Generated by Django 4.2.5 on 2023-11-03 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_billing_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing',
            name='status',
        ),
    ]
