# Generated by Django 4.2.5 on 2023-11-03 14:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_billing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
