# Generated by Django 4.2.5 on 2023-11-04 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_billing_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='billing_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.billing'),
        ),
    ]
