# Generated by Django 4.2.5 on 2023-11-04 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_account_billing_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='payment_receipt_image',
            field=models.ImageField(blank=True, null=True, upload_to='profs/'),
        ),
        migrations.AlterField(
            model_name='account',
            name='ref_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
