# Generated by Django 4.2.5 on 2023-09-08 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emergencyinformation',
            options={'verbose_name': 'Emergency Information', 'verbose_name_plural': 'Emergency Informations'},
        ),
        migrations.AddField(
            model_name='emergencyinformation',
            name='emergency_detail_address',
            field=models.TextField(default='New Israel, Makilala, North Cotabato, 9401', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emergencyinformation',
            name='emergency_detail_lastname',
            field=models.CharField(default='Naquines', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emergencyinformation',
            name='emergency_detail_middlename',
            field=models.CharField(default='Geraldez', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emergencyinformation',
            name='emergency_detail_name',
            field=models.CharField(default='Letecia', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emergencyinformation',
            name='emergency_detail_relation',
            field=models.CharField(default='Mother', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emergencyinformation',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='emergencyinformation',
            table='emergency_detail_tbl',
        ),
    ]
