# Generated by Django 4.2.5 on 2023-09-08 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_emergencyinformation_emergency_detail_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyinformation',
            name='user_id',
            field=models.ForeignKey(help_text='Select boader name', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='emergencyinformation',
            unique_together={('user_id',)},
        ),
    ]
