# Generated by Django 4.2.5 on 2023-09-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_customuser_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='student_id',
            field=models.CharField(default=-65675, max_length=255),
            preserve_default=False,
        ),
    ]
