# Generated by Django 4.2.5 on 2023-09-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_customuser_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyinformation',
            name='emergency_detail_gender',
            field=models.TextField(choices=[('M', 'Male'), ('F', 'Female')], default='Female', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emergencyinformation',
            name='emergency_detail_mobile_number',
            field=models.CharField(default='09060734366', help_text='Enter parent lastname', max_length=255),
            preserve_default=False,
        ),
    ]
