# Generated by Django 4.2.5 on 2023-09-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_emergencyinformation_emergency_detail_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emergencyinformation',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
