# Generated by Django 4.2.5 on 2023-09-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dormitory',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
