# Generated by Django 4.2.5 on 2023-11-04 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0005_alter_room_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_image',
            field=models.ImageField(null=True, upload_to='rooms/'),
        ),
    ]
