# Generated by Django 4.2.5 on 2023-12-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dormitory', '0006_room_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_location',
            field=models.CharField(choices=[('South Wing', 'South Wing'), ('North Wing', 'North Wing')], help_text='Select room location', max_length=255, null=True),
        ),
    ]
