# Generated by Django 4.2.5 on 2023-09-08 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dormitory', '0005_alter_room_room_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_status', models.TextField(choices=[('APPROVED', 'ACCEPTED'), ('UNDER CHECKING', 'UNDER CHECKING'), ('DECLINED', 'DECLINED')])),
                ('is_declined', models.BooleanField(default=False)),
                ('decline_reason', models.TextField(max_length=255)),
                ('date_reserved', models.DateTimeField(auto_now=True)),
                ('dorm_id', models.ForeignKey(help_text='Select dormitory', on_delete=django.db.models.deletion.CASCADE, to='dormitory.dormitory')),
                ('room_id', models.ForeignKey(help_text='Select room', on_delete=django.db.models.deletion.CASCADE, to='dormitory.room')),
                ('user_id', models.ForeignKey(help_text='Select user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
