# Generated by Django 4.2.5 on 2023-09-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_alter_reservation_options_alter_reservation_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='is_declined',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='decline_reason',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
