# Generated by Django 4.2.5 on 2023-09-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_remove_reservation_is_declined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_status',
            field=models.TextField(choices=[('APPROVED', 'ACCEPTED'), ('UNDER CHECKING', 'UNDER CHECKING'), ('DECLINED', 'DECLINED')], null=True),
        ),
    ]
