# Generated by Django 4.2.5 on 2023-09-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_alter_reservation_reservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='decline_reason',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_status',
            field=models.TextField(blank=True, choices=[('APPROVED', 'ACCEPTED'), ('UNDER CHECKING', 'UNDER CHECKING'), ('DECLINED', 'DECLINED')], null=True),
        ),
    ]
