# Generated by Django 4.2.5 on 2023-09-23 10:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0008_remove_reservation_id_reservation_reservation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='move_in_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
