# Generated by Django 4.2.5 on 2023-09-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0010_alter_reservation_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='move_in_date',
            field=models.DateField(),
        ),
    ]
