# Generated by Django 4.2.5 on 2023-09-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0011_alter_reservation_move_in_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_fee',
            field=models.FloatField(default=800.0),
            preserve_default=False,
        ),
    ]
